### ISSUE TITLE
RFE: add test failure section that correlates test failures and scenarios

### ISSUE THREAD

**Issue by kdelee** [ansible/tower-dashboard#27]
Right now you have to dig into each result and manually figure out if the test is failing on multiple platforms (e.g. is it only on RHEL8 or is it across the board or is it only cluster?)

- [x] Mock up presentation
- [x] Figure out how to do the data processing of the junit test results + where this should happen
- [x] figure out way to post data to the dashboard
- [ ] report more work item here ...

**Comment by kdelee** [comment]
I am imagining a section where we can collapse/expand the traceback for each of the platforms where it failed.

Now that we have the `sign_off_jobs` table, we could possbly create a new table:

`failed_tests` that has the fields
```
CREATE TABLE sign_off_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tower_id INTEGER NOT NULL,
  job_id INTEGER NOT NULL,
  error_msg TEXT NOT NULL
  test_name TEXT NOT NULL
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```
where `tower_id` is a reference to the id of the tower_versions table https://github.com/ansible/tower-dashboard/blob/5ea0d2dd5d7eca48c3135360fa11445415b8be89/towerdashboard/schema.sql#L23
and `job_id` is a reference to the `sign_off_jobs` table https://github.com/ansible/tower-dashboard/blob/5ea0d2dd5d7eca48c3135360fa11445415b8be89/towerdashboard/schema.sql#L55


We would then end up with an entry for every failed test. We could then group them together based on having the same `tower_id` and `test_name`. I'm imagining 
```
[ 'devel' : [
     [ 
       { 'test_name': [ list of failed_test objects for this test name and tower_id] }.
       {'another_test' : [ list of failed_test object for this test name and tower_id]}
     ],
  'release_3.6.3' :      [ 
       { 'test_name': [ list of failed_test objects for this test name and tower_id] }.
       {'another_test' : [ list of failed_test object for this test name and tower_id]}
     ]
]
```

**Comment by fpjrh** [comment]
I like the idea that you're presenting here @kdelee ; a couple of additional thoughts around this area:
- can we extend the dashboard to show a representation of overall progress that we are making against features? this is particularly interesting for the next release under development and would provide insight into our overall progress
- during implementation can we reach out to Yanis to ensure that we align with the direction that we want to take for the overall Ansible Automation Platform?

**Comment by nixocio** [comment]
After a call with @appuk we decided about the following next steps:

1. Investigate how get the junit data from Jenkins Pipeline to the dashboard database.
Evaluate the usage of https://github.com/ansible/tower-qa/blob/devel/scripts/merge_junit
2. Adjust the endpoint to accept a POST request with the previous data.
3. Tweak UI and ask for feedback for the others.

@appuk, please, feel free to expand this.

**Comment by kdelee** [comment]
Going to call this done for now and track future enhancements in other work items. Great job yall!!!!
