### ISSUE TITLE
Dashboard fails with 500 when too many branch in ansible/tower-qa

### ISSUE THREAD

**Issue by Spredzy** [ansible/tower-dashboard#30]
The way we retrieve the latest version under test is by retrieving all the branches that starts with a release version (ie. `release_3.6`) and get an array out of it (ie `['release_3.6.0`, 'release_3.6.1', 'release_3.6.2']`) and retrieving the last item of this array. 

https://github.com/ansible/tower-dashboard/blob/master/towerdashboard/jenkins/base.py#L164-L167

Now when we retrieve the array of branches, we retrieve only 100 branch (https://github.com/ansible/tower-dashboard/blob/master/towerdashboard/github.py#L45-L51), when `ansible/tower-qa`` goes over 100 branches the actual branch. might or might not be in the array and then fails and leads to the following failures

![Screenshot_2019-12-05 IndexError list index out of range Werkzeug Debugger](https://user-images.githubusercontent.com/1191411/70224805-2db5d280-174e-11ea-807e-2c4756694110.png)

Possible solution:

  * Recursively pull branches so our array always containss *all* branches
  * Look if Github API allows to sspecify a substring the branch must contain (ie. release) so the number would be way lower and always true.

**Comment by kdelee** [comment]
I suspect there being more than X number of branches on another repo might cause this...

**Comment by nixocio** [comment]
Let me take a look into this one.
