### ISSUE TITLE
first click to hide nav bar doesn't hide nav bar

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/tower-dashboard#85]
### Steps to reproduce
* go to /jenkins/releases
* click the hamburger to hide

### Expected
* for the menu to hide

### Actual
* Doesn't hide until the **second** click

**Comment by appuk** [comment]
Yeah, I observed this behavior on Friday, I think it is a focus issue (it does not work the first time since the focus was not on the navigation bar) I will try to figure the issue out today, hopefully with the help of someone from UI
Thanks for opening the bug!

**Comment by jainnikhil30** [comment]
@appuk If you haven't already got a fix for it, is it fine if I create a PR ? I think I have a working fix, which I tested locally.
